
export const ACTION_TYPES = {
    FETCH_START: "FETCH_START",
    FETCH_ACTIVITIES_SUCCESS: "FETCH_ACTIVITIES_SUCCESS",
    FETCH_PROJECTS_SUCCESS : "FETCH_PROJECTS_SUCCESS",
    FETCH_ERROR: "FETCH_ERROR"
};